config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  get 'likes/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root 'users#index'
  resources :users, only: %i[index show] do
    resources :posts do
      resources :comments, only: %i[create]
      resources :likes, only: %i[create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'

  after_save :update_post_comments_counter

  def update_post_comments_counter
    post.comments_counter = 0 if post.comments_counter.nil?
    post.comments_counter += 1
    post.save
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'

  after_save :update_post_likes_counter

  def update_post_likes_counter
    post.likes_counter = 0 if post.likes_counter.nil?
    post.likes_counter += 1
    post.save
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greated_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greated_than_or_equal_to: 0 }

  has_many :likes
  has_many :comments
  belongs_to :author, class_name: 'User'

  after_create :update_user_posts_counter

  def update_user_posts_counter
    author.posts_counter = 0 if author.posts_counter.nil?
    author.posts_counter += 1
    author.save
  end

  def most_recent_comments
    comments.last(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :bio, presence: true
  validates :posts_counter, numericality: { only_integer: true, greated_than_or_equal_to: 0 }

  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  def most_recent_posts
    posts.last(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    User.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    @comment = current_user.comments.new(params.require(:comment).permit(:text).merge(post_id: post.id))
    if @comment.save
      flash[:alter] = 'Created New Comment succesfully'
    else
      flash.now[:notice] = 'Failed to Create a New Comment'
    end
    redirect_to [:user_post, { id: post.id.to_s }]
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    @userid = params[:u_id]
    @like = current_user.likes.new(post_id: post.id)
    if @like.save
      flash[:alert] = 'Added new like'
    else
      flash.now[:notice] = 'Failed to add new like'
    end
    redirect_to [:user_post, { id: post.id.to_s, user_id: @userid }]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.includes(:comments).find(params[:id])
    @post_counter = params[:post_counter]
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(params.require(:post).permit(:title, :text).merge(author_id: current_user.id))
    @post.likes_counter = 0
    @post.comments_counter = 0
    if @post.save
      flash[:alert] = 'Created New Post succesfully'
      redirect_to [:user_posts]
    else
      flash.now[:notice] = 'Failed to Create a New Post'
      redirect_to [:new_user_post]
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.includes(:posts).order(id: :desc)
  end

  def show
    @user = User.includes(:posts).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def any_comments?(post)
    post.comments
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def any_posts?(user)
    user.posts.last
  end
end

app/views/comments/_comment.html.erb
<div class="comments-div">
  <div class="comment">
   <span><%= comment.author.name %>: <%= comment.text %></span>
  </div> 
</div>

app/views/comments/_form.html.erb
<section class="form-section">
    <h1>Create new comment</h1>
<%= form_with model: @comment, url: user_post_comments_url(post_id: @post.id) ,class: 'post-form' do |f|%>
    <%= f.label :text %>
    <br>
    <%= f.text_area :text %>
    <br>
    <%= f.submit "Submit" %>
<% end %>
</section>

app/views/comments/new.html.erb
<section class="form-section">
    <h1>Create new comment</h1>
    <%= render "form" %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href='https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap' 
rel='stylesheet' type='text/css'>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/29d7bf5b00.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
    <footer class="footer">
    <div class="footer-div">//</div>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: [:user, @post], class: 'post-form' do |f|%>
  <%= f.label :title %>
  <br>
  <%= f.text_field :title %>
  <br>
  <%= f.label :text %>
  <br>
  <%= f.text_area :text %>
  <br>
  <%= f.submit "Submit" %>
<% end %>

app/views/posts/_post.html.erb
<div class="all-post-div">
  <%= link_to(user_post_path(@user, post,post_counter: post_counter+1)) do%>
    <div class="post-div">
      <p><strong>Post #<%= post_counter += 1 %></strong></p>
      <h3><%= post.title %></h3>
      <p> <%= post.text %> </p>
      <span>Comments <%= post.comments_counter %> Likes <%= post.likes_counter %></span>
    </div>
    <div class="comment-container"><%= render post.most_recent_comments %></div>
  <% end %>  
</div>

app/views/posts/index.html.erb
<section>
  <div class="flash">
    <% flash.each do |name, msg| -%>
      <%= content_tag :span, msg, class: name %>
    <% end -%>
  </div>
  <%= render @user %>
  <%= render @posts %>
</section>

app/views/posts/new.html.erb
<section class="form-section">
    <h1>Create new post</h1>
    <%= render "form" %>
</section>

app/views/posts/show.html.erb
<section>
 <div class="flash">
  <% flash.each do |name, msg| -%>
    <%= content_tag :span, msg, class: name %>
 <% end -%>
</div>
  <div class="post">
    <div class="post-header-div"> 
    <h2>Posts  #<%= @post_counter %> by <%= @user.name %></strong></h2>
    <span>Comments <%= @post.comments_counter %> Likes <%= @post.likes_counter %></span>
    </div>
    <h2><%= @post.title %></h2>
    <p><%= @post.text %></p>
    <%= link_to likes_create_path(post_id: @post.id.to_s,u_id: @user.id.to_s), method: :put, class: 'like' do %>
      <i class="far fa-heart"></i>
    <% end %>
  </div>
  <%= render @post.comments if any_comments?(@post) %>
  <%= render "comments/form" %>
</section>

app/views/shared/_comments.html.erb
<div class="comment">
  <span><%= comment.author.name %>: <%= comment.text %></span>
</div> 

app/views/users/_post.html.erb
<div class="all-post-div">
    <div class="post-div">
      <p><strong>Post #1</strong></p>
      <h3><%= post.title %></h3>
      <p> <%= post.text %> </p>
      <span>Comments <%= post.comments_counter %> Likes <%= post.likes_counter %></span>
    </div>
</div>

app/views/users/_user.html.erb
<%= link_to(user) do %>
<div class="user-div">
  <div class="photo-div">
    <img src="<%= user.photo %>">
  </div>
  <div class="user-details-div">
    <h2 class="user-name-h2"><%= user.name %></h2>
    <span class="user-posts-details">Number of posts <%= user.posts_counter %></span>
  </div>
</div>
<% end %>

app/views/users/_users.html.erb
<%= link_to(user) do %>
<div class="user-div">
  <div class="photo-div">
    <img src="<%= user.photo %>">
  </div>
  <div class="user-details-div">
    <p class="user-name-p"><%= user.name %></p>
    <span class="user-posts-details">Number of posts <%= user.posts_counter %></span>
  </div>
</div>

app/views/users/index.html.erb
<section>
    <%= render @users %>
</section>

app/views/users/show.html.erb
<section>
  <%= render @user %>
  <div class="user-bio">
    <h2>Bio</h2>
    <p><%= @user.bio %></p>
  </div>
  <div class="user-posts">
    <%= render partial: "users/post", locals: {post: @user.posts.last} if any_posts?(@user) %>
  </div>
  <%= button_to 'See all posts', user_posts_url(:user_id => @user.id), method: :get, class: 'user-post-buttons'  if any_posts?(@user)%>
  <%= link_to(new_user_post_path(user_id: @user.id),class: 'create-post-link') do %><button class="user-post-buttons" >Create new post</button><% end %>
</section>